use TPTST


UPDATE    IV00102
SET              PORECEIPTBIN = 'RECEIVING', PORETRNBIN = 'RECEIVING', SOFULFILLMENTBIN = 'SHIPSTAGE', SORETURNBIN = 'SHIPSTAGE', BOMRCPTBIN = 'MFG RECEIPT', 
                      MATERIALISSUEBIN = 'WIP', MORECEIPTBIN = 'MFG RECEIPT'
WHERE     (LOCNCODE = '0ca')  OR
                      (LOCNCODE = '1ca') OR
                      (LOCNCODE = '2ca') 