--select * from IV00102

WHERE LOCNCODE ='0CA'

UPDATE    IV00102
SET              PORECEIPTBIN = 'RECEIVING', PORETRNBIN = 'RECEIVING', SOFULFILLMENTBIN = 'SHIPSTAGE', SORETURNBIN = 'SHIPSTAGE', BOMRCPTBIN = 'MFG RECEIPT', 
                      MATERIALISSUEBIN = 'WIP', MORECEIPTBIN = 'MFG RECEIPT'
WHERE     LOCNCODE ='2VA'

/*
in('0CA',
'0GA',
'0IN',
'0OR',
'0TX',
'0VA',
'1CA',
'1GA',
'1IN',
'1OR',
'1TX',
'1VA',
'2CA',
'2GA',
'2IN',
'2OR',
'2TX',
'2VA')
*/