INSERT  [TPSPT].[dbo].[_Sales_2013_Current]
       select
           [Business Unit]
           ,[SOP Type]
           ,[SOP Number]
           ,[Customer PO Number]
           ,[Item Number]
           ,[Item Description from Item Master]
           ,[QTY]
           ,[Unit Cost]
           ,[Extended Cost]
           ,[Unit Price]
           ,[Extended Price]
           ,[Customer Number]
           ,[Customer Class]
           ,[Customer Name from Customer Master]
           ,[Document Date]
           ,[Doc Month]
           ,[Document Status]
           ,[Item Class Code]
           ,[Class Description]
           ,[Sales Category]
           ,[Original Number]
           ,[Posting Status]
           ,[Requested Ship Date]
           ,[Sales Territory from Customer Master]
           ,[Salesperson ID from Customer Master]
           ,[State from Sales Transaction]
           ,[Item Description]
           ,[Location Code]
           ,[Document Year]
           from vw_Sales_2013_Current